import { v4 as uuidv4 } from 'uuid';

export const sampleData = () => [
  {
    id: uuidv4(),
    name: 'Platform Launch',
    isActive: false,
    columns: [
      { id: 1, name: 'Todo' },
      { id: 2, name: 'Doing' },
      { id: 3, name: 'Testing' },
      { id: 4, name: 'Done' },
    ],
    tasks: [
      {
        id: uuidv4(),
        title: 'Build UI for onboarding flow',
        description: '',
        statusId: 1,
        taskIdentifier: 'NUC-1',
        dateCreate: '2021-01-11',
      },
      {
        id: uuidv4(),
        title: 'Build UI for search',
        description: '',
        statusId: 1,
        taskIdentifier: 'NUC-1',
        dateCreate: '2021-01-10',
      },
      {
        id: uuidv4(),
        title: 'Build settings UI',
        description: '',
        statusId: 1,
        taskIdentifier: 'NUC-2',
        dateCreate: '2021-01-09',
      },
      {
        id: uuidv4(),
        title: 'QA and test all major user journeys',
        description:
          'Once we feel version one is ready, we need to rigorously test it both internally and externally to identify any major gaps.',
        statusId: 1,
        taskIdentifier: 'NUC-3',
        dateCreate: '2021-01-08',
      },
      {
        id: uuidv4(),
        title: 'Design settings and search pages',
        description: '',
        statusId: 2,
        taskIdentifier: 'NUC-4',
        dateCreate: '2021-01-07',
      },
      {
        id: uuidv4(),
        title: 'Add account management endpoints',
        description: '',
        statusId: 2,
        taskIdentifier: 'NUC-5',
        dateCreate: '2021-01-06',
      },
      {
        id: uuidv4(),
        title: 'Design onboarding flow',
        description: '',
        statusId: 2,
        taskIdentifier: 'NUC-6',
        dateCreate: '2021-01-05',
      },
      {
        id: uuidv4(),
        title: 'Add search enpoints',
        description: '',
        statusId: 2,
        taskIdentifier: 'NUC-7',
        dateCreate: '2021-01-04',
      },
      {
        id: uuidv4(),
        title: 'Add authentication endpoints',
        description: '',
        statusId: 2,
        taskIdentifier: 'NUC-8',
        dateCreate: '2021-01-03',
      },
      {
        id: uuidv4(),
        title: 'Research pricing points of various competitors and trial different business models',
        description:
          "We know what we're planning to build for version one. Now we need to finalise the first pricing model we'll use. Keep iterating the subtasks until we have a coherent proposition.",
        statusId: 2,
        taskIdentifier: 'NUC-9',
        dateCreate: '2021-01-02',
        userId: 1,
      },
      {
        id: uuidv4(),
        title: 'Conduct 5 wireframe tests',
        description: 'Ensure the layout continues to make sense and we have strong buy-in from potential users.',
        statusId: 3,
        taskIdentifier: 'NUC-10',
        dateCreate: '2021-11-01',
        userId: 2,
      },
      {
        id: uuidv4(),
        title: 'Create wireframe prototype',
        description: 'Create a greyscale clickable wireframe prototype to test our asssumptions so far.',
        statusId: 3,
        taskIdentifier: 'NUC-11',
        dateCreate: '2021-02-02',
        userId: 7,
      },
      {
        id: uuidv4(),
        title: 'Review results of usability tests and iterate',
        description: "Keep iterating through the subtasks until we're clear on the core concepts for the app.",
        statusId: 3,
        taskIdentifier: 'NUC-12',
        dateCreate: '2022-04-02',
      },
      {
        id: uuidv4(),
        title: 'Create paper prototypes and conduct 10 usability tests with potential customers',
        description: '',
        statusId: 3,
        taskIdentifier: 'NUC-13',
        dateCreate: '2023-05-11',
      },
      {
        id: uuidv4(),
        title: 'Market discovery',
        description:
          'We need to define and refine our core product. Interviews will help us learn common pain points and help us define the strongest MVP.',
        statusId: 3,
        taskIdentifier: 'NUC-14',
        dateCreate: '2022-04-01',
      },
      {
        id: uuidv4(),
        title: 'Competitor analysis',
        description: '',
        statusId: 4,
        taskIdentifier: 'NUC-15',
        dateCreate: '2022-02-01',
      },
      {
        id: uuidv4(),
        title: 'Research the market',
        description: 'We need to get a solid overview of the market to ensure we have up-to-date estimates of market size and demand.',
        statusId: 4,
        taskIdentifier: 'NUC-16',
        dateCreate: '2022-01-01',
      },
    ],
  },
];
